# Generated by Django 4.2.18 on 2025-01-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the name of author', max_length=100, verbose_name='The name of author')),
                ('last_name', models.CharField(help_text='Enter the last name of author', max_length=100, verbose_name='Last name of author')),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter the birthday of author', null=True, verbose_name='Birthday')),
                ('date_of_death', models.DateField(blank=True, help_text='Enter date of death', null=True, verbose_name='Date of death')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the name of the book', max_length=200, verbose_name='Name of the book')),
                ('summary', models.TextField(help_text='Enter a short discription of the book', max_length=1000, verbose_name='Book summary')),
                ('isbn', models.CharField(help_text='Must contain 13 characters', max_length=13, verbose_name='ISBN of the book')),
                ('author', models.ManyToManyField(help_text='Choose the author of the book', null=True, to='catalog.author', verbose_name='The author of the book')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the genre of the book', max_length=200, verbose_name='Genre of the book')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter language of book', max_length=20, verbose_name='Language of book')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the status of the book instance', max_length=20, verbose_name='The status of the book instance')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_nom', models.CharField(help_text='Enter the inventory number of the instance', max_length=20, null=True, verbose_name='The inventory number of the instance')),
                ('imprint', models.CharField(help_text='Enter the publisher and the year of release', max_length=200, verbose_name='Publisher')),
                ('due_back', models.DateField(blank=True, help_text='Enter the end of the status period', null=True, verbose_name='End date of the status')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text='Change the instance state', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='The status of the book instance')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(help_text='Choose a genre for the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Genre of the book'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Choose a language for the book', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Language of the boot'),
        ),
    ]
