# Generated by Django 4.2.18 on 2025-01-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Choose the author of the book', to='catalog.author', verbose_name='The author of the book'),
        ),
    ]
